# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eda2468f8e7462558d7806711084e844cfee85bef6bf817160f5b029d10b412d292af2cc2e103ec8c0a80fa5cdb19732733ec0a67f8475a96bc6442bc998a581

test:
  secret_key_base: da4b0e2a630d0a60b2ca86ff668dca18f3b9ddfa52d79f784b694b6a05ed0589d16e96632381df950a266afb76b106c918afee8113c5e70951d3272cbdb409dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
